##########################################################
# Created by: Ankit Rajpoot                                 
# Created on: Wednesday 26 October 2022 04:25:20 PM IST 
##########################################################


SRCDIR = ../src
INCLUDEDIR = ../include
OBJDIR = ../obj
BINDIR = ../bin

CFLAGS = -c -g -Wall -I${INCLUDEDIR} 


all:
	gcc ${CFLAGS}  ${SRCDIR}/main.c -o ${OBJDIR}/main.o 
	gcc ${OBJDIR}/main.o  -o ${BINDIR}/Structures.exe


clean:

	rm ${OBJDIR}/main.o ${BINDIR}/Structures.exe


#################### End of Makefile #####################
